const labels: Record<string, string> = {
  active: "Aktív",
  accepted: "Elfogadva",
  applied: "Alkalmazva",
  blocked: "Nem indítható",
  bounced: "Visszapattant",
  cancelled: "Leállítva",
  complained: "Panasz érkezett",
  declined: "Elutasítva",
  disabled: "Letiltva",
  empty: "Nincs találat",
  eligible: "Ajánlható",
  expired: "Lejárt",
  failed: "Sikertelen",
  issued: "Felhasználható",
  paused: "Szüneteltetve",
  pending: "Döntésre vár",
  preview: "Ellenőrzésre vár",
  processing: "Feldolgozás alatt",
  queued: "Küldésre vár",
  ready: "Indításra kész",
  redeemed: "Beváltva",
  revoked: "Visszavonva",
  retryable_failed: "Újrapróbálásra vár",
  scheduled: "Ütemezve",
  sent: "Elküldve",
  suppressed: "Küldés letiltva",
  unsupported: "Nem elérhető",
  owner: "Tulajdonos",
  staff: "Munkatárs",
  operator: "Üzemeltető",
  user: "Felhasználó",
  flash_campaign: "Villámkampány",
  offer_list: "Ajánlatlista",
  personal_offer: "Személyes ajánlat",
  COMPATIBLE_ACCESSORY: "Kompatibilis kiegészítő",
  REPLENISHMENT: "Ismételt vásárlás",
  SAME_CATEGORY: "Kapcsolódó kategória",
  IN_APP_THREAD_AVAILABLE: "Megjelent a beszélgetésben",
  READY_FOR_RESEND: "E-mail küldésre kész",
  READY_FOR_CONFIGURED_TRANSPORT: "Küldésre kész",
  TRANSPORT_NOT_CONFIGURED: "A csatorna nincs beállítva",
  DELIVERY_SEND_IN_PROGRESS: "A küldés folyamatban van",
  EMAIL_HARD_BOUNCE: "A címzett levelezőrendszere elutasította",
  EMAIL_COMPLAINT: "A címzett kéretlen levélként jelölte",
  CONSENT_NOT_GRANTED: "Nincs megfelelő hozzájárulás",
  CONSENT_WITHDRAWN: "A hozzájárulást visszavonták",
  BUYER_RELATIONSHIP_INACTIVE: "A vásárlói kapcsolat nem aktív",
};

export function businessLabel(value: string | null | undefined, fallback = "Nincs megadva") {
  if (!value) return fallback;
  if (labels[value]) return labels[value];
  const readable = value.toLocaleLowerCase("hu-HU").replaceAll("_", " ");
  return readable.charAt(0).toLocaleUpperCase("hu-HU") + readable.slice(1);
}
