import "server-only";
import mongoose from "mongoose";
import { sellerAccess } from "@/catalog/service";
import { connectDatabase } from "@/lib/database";
import { Artifact } from "@/artifacts/models";
import { PostalFulfillment, PostalFulfillmentEvent } from "./models";
import { nextFulfillmentStatus, type PostalFulfillmentStatus } from "./fulfillment-core";

export class FulfillmentError extends Error { constructor(public code:"FORBIDDEN"|"NOT_FOUND"|"INVALID"|"CONFLICT"|"UNAVAILABLE"){super(code);} }

type FulfillmentRow={_id:{toString():string};printSnapshotId:{toString():string};artifactId:{toString():string};status:PostalFulfillmentStatus;version:number;printedAt?:Date|null;postedAt?:Date|null;createdAt:Date};
function output(row:FulfillmentRow){return{id:row._id.toString(),snapshotId:row.printSnapshotId.toString(),artifactId:row.artifactId.toString(),status:row.status,version:row.version,printedAt:row.printedAt??null,postedAt:row.postedAt??null,createdAt:row.createdAt};}

export async function listPostalFulfillments(userId:string,sellerSlug:string){const access=await sellerAccess(userId,sellerSlug).catch(()=>{throw new FulfillmentError("FORBIDDEN");});const rows=await PostalFulfillment.find({sellerId:access.seller._id}).sort({createdAt:-1,_id:-1}).limit(100).lean();return{seller:{id:access.seller._id.toString(),name:access.seller.name,slug:access.seller.slug},fulfillments:rows.map(output)};}

export async function transitionPostalFulfillment(userId:string,sellerSlug:string,input:{fulfillmentId:unknown;version:unknown;action:unknown;idempotencyKey:unknown}){if(typeof input.fulfillmentId!=="string"||!mongoose.isValidObjectId(input.fulfillmentId)||!Number.isInteger(Number(input.version))||typeof input.idempotencyKey!=="string"||!/^[A-Za-z0-9:_-]{8,180}$/.test(input.idempotencyKey))throw new FulfillmentError("INVALID");const access=await sellerAccess(userId,sellerSlug).catch(()=>{throw new FulfillmentError("FORBIDDEN");});await connectDatabase();const session=await mongoose.startSession();try{return await session.withTransaction(async()=>{const existingEvent=await PostalFulfillmentEvent.findOne({sellerId:access.seller._id,idempotencyKey:input.idempotencyKey}).session(session).lean();if(existingEvent){const existing=await PostalFulfillment.findOne({_id:existingEvent.fulfillmentId,sellerId:access.seller._id}).session(session).lean();if(!existing)throw new FulfillmentError("NOT_FOUND");return output(existing);}const current=await PostalFulfillment.findOne({_id:input.fulfillmentId,sellerId:access.seller._id}).session(session).lean();if(!current)throw new FulfillmentError("NOT_FOUND");let next:PostalFulfillmentStatus;try{next=nextFulfillmentStatus(current.status,input.action);}catch{throw new FulfillmentError("CONFLICT");}const now=new Date();const set:Record<string,unknown>={status:next};if(next==="printed"){set.printedAt=now;set.printedByUserId=userId;}else{set.postedAt=now;set.postedByUserId=userId;}const updated=await PostalFulfillment.findOneAndUpdate({_id:current._id,sellerId:access.seller._id,status:current.status,version:Number(input.version)},{$set:set,$inc:{version:1}},{new:true,session}).lean();if(!updated)throw new FulfillmentError("CONFLICT");await PostalFulfillmentEvent.create([{sellerId:access.seller._id,fulfillmentId:current._id,fromStatus:current.status,toStatus:next,actorUserId:userId,occurredAt:now,idempotencyKey:input.idempotencyKey}],{session});return output(updated);});}finally{await session.endSession();}}

export async function verifyFulfillmentArtifact(userId:string,sellerSlug:string,fulfillmentId:string){const access=await sellerAccess(userId,sellerSlug).catch(()=>{throw new FulfillmentError("FORBIDDEN");});if(!mongoose.isValidObjectId(fulfillmentId))throw new FulfillmentError("INVALID");const row=await PostalFulfillment.findOne({_id:fulfillmentId,sellerId:access.seller._id}).lean();if(!row)throw new FulfillmentError("NOT_FOUND");const artifact=await Artifact.findOne({_id:row.artifactId,sellerId:access.seller._id,status:"ready",retentionUntil:{$gt:new Date()}}).lean();if(!artifact)throw new FulfillmentError("UNAVAILABLE");return output(row);}
