import "server-only";
/* eslint-disable @typescript-eslint/no-explicit-any -- provider and Mongoose payloads are normalized at this boundary. */
import { createHash, randomUUID } from "node:crypto";
import mongoose from "mongoose";
import { sellerAccess } from "@/catalog/service";
import { Artifact } from "@/artifacts/models";
import { privateBlobReadUrl } from "@/lib/blob";
import { connectDatabase } from "@/lib/database";
import { withSellerTenant, withTenantBypass } from "@/lib/tenant";
import { PostalFulfillment, PostalProviderEvent, PostalSubmission, PostalSubmissionEvent } from "./models";
import { mayApplyProviderStatus, normalizeProviderStatus, retryDelayMs, verifyPostalProviderSignature, type SubmissionStatus } from "./provider-core";

export class PostalProviderError extends Error{constructor(public code:"FORBIDDEN"|"NOT_FOUND"|"INVALID"|"CONFLICT"|"UNAVAILABLE"){super(code);}}
const workerId=`postal-${process.pid}-${randomUUID()}`,lockMs=2*60_000;
type Config={provider:"http";endpoint:string;token:string;callbackSecret:string;publicBaseUrl:string};
function config():Config|null{if(process.env.POSTAL_DELIVERY_PROVIDER!=="http")return null;const endpoint=process.env.POSTAL_PROVIDER_ENDPOINT??"",token=process.env.POSTAL_PROVIDER_TOKEN??"",callbackSecret=process.env.POSTAL_PROVIDER_WEBHOOK_SECRET??"",publicBaseUrl=process.env.POSTAL_PUBLIC_BASE_URL??process.env.APP_URL??"";if(!endpoint.startsWith("https://")||token.length<16||callbackSecret.length<32||!publicBaseUrl.startsWith("https://"))return null;return{provider:"http",endpoint,token,callbackSecret,publicBaseUrl};}
export function postalProviderReadiness(){return config()?{enabled:true as const,reasonCode:"POSTAL_PROVIDER_READY"}:{enabled:false as const,reasonCode:"POSTAL_PROVIDER_NOT_CONFIGURED"};}
async function event(input:{sellerId:unknown;submissionId:unknown;status:SubmissionStatus;reasonCode:string;occurredAt:Date;actorUserId?:unknown;providerEventId?:string|null},session?:mongoose.ClientSession){const rows=[{...input,actorUserId:input.actorUserId??null,providerEventId:input.providerEventId??null}];if(session)await PostalSubmissionEvent.create(rows,{session});else await PostalSubmissionEvent.create(rows);}
function output(row:Record<string,unknown>){const id=row._id as{toString():string};return{id:id.toString(),status:row.status,provider:row.provider,providerRef:row.providerRef??null,attemptCount:row.attemptCount,nextAttemptAt:row.nextAttemptAt??null,lastErrorCode:row.lastErrorCode??null};}

export async function queuePostalSubmission(userId:string,sellerSlug:string,fulfillmentId:unknown,idempotencyKey:unknown){if(typeof fulfillmentId!=="string"||!mongoose.isValidObjectId(fulfillmentId)||typeof idempotencyKey!=="string"||!/^[A-Za-z0-9:_-]{8,180}$/.test(idempotencyKey))throw new PostalProviderError("INVALID");const cfg=config();if(!cfg)throw new PostalProviderError("UNAVAILABLE");const access=await sellerAccess(userId,sellerSlug).catch(()=>{throw new PostalProviderError("FORBIDDEN");});const fulfillment=await PostalFulfillment.findOne({_id:fulfillmentId,sellerId:access.seller._id,status:"ready"}).lean();if(!fulfillment)throw new PostalProviderError("CONFLICT");const artifact=await Artifact.findOne({_id:fulfillment.artifactId,sellerId:access.seller._id,status:"ready",retentionUntil:{$gt:new Date()}}).lean();if(!artifact)throw new PostalProviderError("UNAVAILABLE");const existing=await PostalSubmission.findOne({sellerId:access.seller._id,$or:[{fulfillmentId:fulfillment._id},{idempotencyKey}]}).lean();if(existing)return output(existing as unknown as Record<string,unknown>);const now=new Date();const row=await PostalSubmission.create({sellerId:access.seller._id,fulfillmentId:fulfillment._id,artifactId:artifact._id,provider:cfg.provider,status:"queued",idempotencyKey,attemptCount:0,maxAttempts:3,nextAttemptAt:now,createdByUserId:userId});await event({sellerId:access.seller._id,submissionId:row._id,status:"queued",reasonCode:"POSTAL_SUBMISSION_QUEUED",occurredAt:now,actorUserId:userId});return output(row.toObject());}

export async function cancelPostalSubmission(userId:string,sellerSlug:string,submissionId:unknown){if(typeof submissionId!=="string"||!mongoose.isValidObjectId(submissionId))throw new PostalProviderError("INVALID");const access=await sellerAccess(userId,sellerSlug).catch(()=>{throw new PostalProviderError("FORBIDDEN");});const now=new Date();const row=await PostalSubmission.findOneAndUpdate({_id:submissionId,sellerId:access.seller._id,status:{$in:["queued","retryable_failed"]}},{$set:{status:"cancelled",cancelledAt:now,completedAt:now,nextAttemptAt:null,lockedUntil:null,lockedBy:null}},{returnDocument: "after"}).lean();if(!row)throw new PostalProviderError("CONFLICT");await event({sellerId:access.seller._id,submissionId:row._id,status:"cancelled",reasonCode:"POSTAL_SUBMISSION_CANCELLED",occurredAt:now,actorUserId:userId});return output(row as unknown as Record<string,unknown>);}

async function submit(row:Record<string,any>,cfg:Config,fetcher:typeof fetch){const artifact=await Artifact.findOne({_id:row.artifactId,sellerId:row.sellerId,status:"ready",retentionUntil:{$gt:new Date()}}).lean();if(!artifact)throw new Error("POSTAL_ARTIFACT_UNAVAILABLE");const signed=await privateBlobReadUrl(artifact.blobKey,{ttlSeconds:10*60,useCache:false});const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10_000);try{const response=await fetcher(cfg.endpoint,{method:"POST",headers:{authorization:`Bearer ${cfg.token}`,"content-type":"application/json","idempotency-key":row.idempotencyKey},body:JSON.stringify({submissionId:row._id.toString(),documentUrl:signed.url,callbackUrl:`${cfg.publicBaseUrl}/api/postal/provider-events`}),signal:controller.signal});if(!response.ok)throw new Error(response.status>=500?"POSTAL_PROVIDER_TRANSIENT":"POSTAL_PROVIDER_REJECTED");const body=await response.json() as{providerRef?:unknown};if(typeof body.providerRef!=="string"||body.providerRef.length>160)throw new Error("POSTAL_PROVIDER_RESPONSE_INVALID");return body.providerRef;}finally{clearTimeout(timeout);}}

export async function processPostalSubmissions(limitValue=10,fetcher:typeof fetch=fetch){await connectDatabase();const cfg=config();if(!cfg)return{processed:0,reasonCode:"POSTAL_PROVIDER_NOT_CONFIGURED"};const limit=Math.min(25,Math.max(1,Math.floor(limitValue))),results:Array<Record<string,unknown>>=[];for(let index=0;index<limit;index++){const now=new Date();const row=await withTenantBypass("postal-provider-global-claim",async()=>await PostalSubmission.findOneAndUpdate({status:{$in:["queued","retryable_failed"]},nextAttemptAt:{$lte:now},$or:[{lockedUntil:null},{lockedUntil:{$lte:now}}]},{$set:{status:"processing",lockedUntil:new Date(now.getTime()+lockMs),lockedBy:workerId,lastAttemptAt:now},$inc:{attemptCount:1}},{returnDocument: "after"}).lean());if(!row)break;await withSellerTenant(row.sellerId,async()=>{try{const providerRef=await submit(row as unknown as Record<string,any>,cfg,fetcher);const finished=await PostalSubmission.findOneAndUpdate({_id:row._id,sellerId:row.sellerId,status:"processing",lockedBy:workerId},{$set:{status:"submitted",providerRef,submittedAt:new Date(),nextAttemptAt:null,lockedUntil:null,lockedBy:null,lastErrorCode:null}},{returnDocument: "after"}).lean();if(finished){await event({sellerId:row.sellerId,submissionId:row._id,status:"submitted",reasonCode:"POSTAL_PROVIDER_ACCEPTED",occurredAt:new Date()});results.push(output(finished as unknown as Record<string,unknown>));}}catch(error){const permanent=/REJECTED|RESPONSE_INVALID|ARTIFACT/.test(error instanceof Error?error.message:"")||row.attemptCount>=row.maxAttempts;const status=permanent?"failed":"retryable_failed",nextAttemptAt=permanent?null:new Date(Date.now()+retryDelayMs(row.attemptCount));const failed=await PostalSubmission.findOneAndUpdate({_id:row._id,sellerId:row.sellerId,status:"processing",lockedBy:workerId},{$set:{status,nextAttemptAt,lockedUntil:null,lockedBy:null,lastErrorCode:permanent?"POSTAL_PROVIDER_PERMANENT_FAILURE":"POSTAL_PROVIDER_TRANSIENT_FAILURE",completedAt:permanent?new Date():null}},{returnDocument: "after"}).lean();if(failed){await event({sellerId:row.sellerId,submissionId:row._id,status,reasonCode:String(failed.lastErrorCode),occurredAt:new Date()});results.push(output(failed as unknown as Record<string,unknown>));}}});}return{processed:results.length,results};}

export async function handlePostalProviderEvent(payload:string,headers:Headers){const cfg=config();if(!cfg)throw new PostalProviderError("UNAVAILABLE");verifyPostalProviderSignature(payload,headers,cfg.callbackSecret);let body:{eventId?:unknown;providerRef?:unknown;status?:unknown;occurredAt?:unknown};try{body=JSON.parse(payload);}catch{throw new PostalProviderError("INVALID");}if(typeof body.eventId!=="string"||typeof body.providerRef!=="string"||body.eventId.length>160||body.providerRef.length>160)throw new PostalProviderError("INVALID");const status=normalizeProviderStatus(body.status),occurredAt=new Date(String(body.occurredAt));if(!Number.isFinite(occurredAt.getTime()))throw new PostalProviderError("INVALID");const payloadHash=createHash("sha256").update(payload).digest("hex");const existing=await withTenantBypass("postal-provider-event-replay",()=>PostalProviderEvent.findOne({provider:cfg.provider,providerEventId:body.eventId}).lean());if(existing)return{action:existing.action,replayed:true};const row=await withTenantBypass("postal-provider-ref-lookup",()=>PostalSubmission.findOne({provider:cfg.provider,providerRef:body.providerRef}).lean());let action="SUBMISSION_NOT_FOUND";if(row&&mayApplyProviderStatus(row.status,status)){await PostalSubmission.updateOne({_id:row._id,sellerId:row.sellerId},{$set:{status,lastErrorCode:status==="failed"?"POSTAL_PROVIDER_REPORTED_FAILURE":null,completedAt:["delivered","failed"].includes(status)?new Date():null}});await event({sellerId:row.sellerId,submissionId:row._id,status,reasonCode:`POSTAL_PROVIDER_${status.toUpperCase()}`,occurredAt,providerEventId:body.eventId});action="STATUS_APPLIED";}else if(row)action="STATUS_IGNORED";await withTenantBypass("postal-provider-event-record",()=>PostalProviderEvent.create({provider:cfg.provider,providerEventId:body.eventId,submissionId:row?._id??null,sellerId:row?.sellerId??null,payloadHash,status,action,occurredAt}));return{action,replayed:false};}
