import { redirect } from "next/navigation";
import { BannerNotice, Button as GdsButton, EmptyState, GdsGrid, GdsIcon, ListingCard, PageHeader, SectionPanel, StatusBadge } from "@discountdirect/gds-client";
import { currentUser } from "@/auth/service";
import { Shell } from "@/components/shell";
import { buyerOffers } from "@/offers/service";
import { respondOfferAction } from "./actions";
export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("hu-HU", { style: "currency", currency: "HUF", maximumFractionDigits: 0 }); const date = new Intl.DateTimeFormat("hu-HU", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Budapest" });
export default async function BuyerOffersPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) { const user = await currentUser(); if (!user) redirect("/sign-in"); const { offers } = await buyerOffers(user.id); const query = await searchParams; return <Shell active="account"><PageHeader title="Ajánlataim" description="Az ajánlat elfogadása csak döntés vagy foglalási szándék; nem fizetés és nem teljesítési igazolás." eyebrow="Személyes ajánlatok" actions={<div className="button-row"><GdsButton component="a" href="/buyer/lists" variant="default" leftSection={<GdsIcon name="List" decorative />}>Ajánlatlisták</GdsButton><GdsButton component="a" href="/buyer/redemptions" variant="default" leftSection={<GdsIcon name="Tag" decorative />}>Kuponok</GdsButton><StatusBadge status="info">{offers.length} ajánlat</StatusBadge></div>} />{query.saved ? <BannerNotice severity="success" variant="compact" message="Az ajánlati döntés rögzítve. Elfogadáskor kupon is létrejön." /> : null}{query.error ? <BannerNotice severity="error" variant="compact" message="Az ajánlat állapota vagy a kampány készlete közben megváltozott." /> : null}<SectionPanel title="Érvényes és korábbi ajánlatok" description="Az ár, kedvezmény és ajánlási indok az ajánlat létrehozásakor rögzített pillanatkép.">{!offers.length ? <EmptyState title="Még nincs ajánlat" description="Az eladó által létrehozott személyes ajánlatok itt jelennek meg." /> : <GdsGrid columns={{ base: 1, md: 2 }}>{offers.map((offer) => <ListingCard key={offer.id} title={offer.product.name} description={offer.reason.text} price={money.format(offer.priceHuf)} mediaSeed={offer.id} mediaOverlay={offer.status === "pending" ? `${offer.discountPct}% kedvezmény` : offer.status} metadata={[{ id: "original", label: "Eredeti ár", value: money.format(offer.originalHuf) }, { id: "expiry", label: "Érvényes", value: date.format(new Date(offer.expiresAt)) }, { id: "reason", label: "Indok", value: offer.reason.code }, ...(offer.campaignId ? [{ id: "campaign", label: "Típus", value: "Villámkampány" }] : [])]} primaryAction={offer.status === "pending" ? <div className="button-row"><form action={respondOfferAction.bind(null, offer.id, offer.version, "accepted")}><GdsButton type="submit" leftSection={<GdsIcon name="Check" decorative />}>{offer.campaignId ? "Lefoglalom" : "Elfogadom"}</GdsButton></form><form action={respondOfferAction.bind(null, offer.id, offer.version, "declined")}><GdsButton type="submit" variant="default" leftSection={<GdsIcon name="Close" decorative />}>Elutasítom</GdsButton></form></div> : undefined} />)}</GdsGrid>}</SectionPanel></Shell>; }
