import { redirect } from "next/navigation";
import { BannerNotice, Button as GdsButton, GdsIcon, PageHeader, SectionPanel, StatusBadge } from "@discountdirect/gds-client";
import { currentUser } from "@/auth/service";
import { Shell } from "@/components/shell";
import { listConnectors } from "@/connectors/service";
import { disableConnectorAction } from "../actions";

export const dynamic="force-dynamic";
export default async function DisableConnectorPage({params,searchParams}:{params:Promise<{sellerSlug:string}>,searchParams:Promise<{provider?:string}>}){const user=await currentUser();if(!user)redirect("/sign-in");const {sellerSlug}=await params;const {provider}=await searchParams;const result=await listConnectors(user.id,sellerSlug).catch(()=>null);if(!result||result.membership.role!=="owner")redirect(`/seller/${sellerSlug}/connectors?error=FORBIDDEN`);const connector=result.connectors.find((item)=>item.provider===provider);if(!connector||connector.status==="disabled")redirect(`/seller/${sellerSlug}/connectors?error=NOT_FOUND`);return <Shell active="seller"><PageHeader eyebrow={result.seller.name} title="Kapcsolat kikapcsolása" description="A kikapcsolás leállítja az új szinkronizálásokat és webáruházi átadásokat. A korábbi futások és normalizált rekordok megmaradnak."/><BannerNotice severity="warning" title="Megerősítés szükséges" message="A művelet után a kapcsolatot újra kell menteni és tesztelni, mielőtt használható lesz."/><SectionPanel title={connector.provider==="shoprenter"?"Shoprenter":"UNAS"} description="Csak az alábbi megerősítő gomb változtat állapotot."><StatusBadge status="warning">{connector.status}</StatusBadge><div className="button-row"><form action={disableConnectorAction.bind(null,sellerSlug,connector.provider,connector.version)}><GdsButton type="submit" leftSection={<GdsIcon name="Close" decorative/>}>Kapcsolat kikapcsolása</GdsButton></form><GdsButton component="a" href={`/seller/${sellerSlug}/connectors`} variant="default">Mégse</GdsButton></div></SectionPanel></Shell>;}
