import mongoose from "mongoose";
import { sellerScopedSchema } from "../lib/tenant-core.ts";

const { Schema, model, models } = mongoose;
const timestamps = { timestamps: true, versionKey: false } as const;
const stepSchema = new Schema({ key: { type: String, required: true, maxlength: 60 }, delayMinutes: { type: Number, required: true, min: 0, max: 525600 }, channel: { type: String, enum: ["in_app", "email", "postal"], required: true }, title: { type: String, required: true, maxlength: 160 } }, { _id: false });

const definitionSchema = new Schema({ sellerId: { type: Schema.Types.ObjectId, required: true, ref: "Seller", index: true }, name: { type: String, required: true, maxlength: 160 }, status: { type: String, enum: ["active", "paused", "retired"], required: true, default: "paused", index: true }, activeVersion: { type: Number, required: true, min: 1 }, clientRequestId: { type: String, required: true, maxlength: 120 }, createdByUserId: { type: Schema.Types.ObjectId, required: true, ref: "User" }, version: { type: Number, required: true, default: 1, min: 1 } }, { ...timestamps, collection: "journey_definitions" });
definitionSchema.index({ sellerId: 1, clientRequestId: 1 }, { unique: true });
definitionSchema.index({ sellerId: 1, status: 1, updatedAt: -1 });

const versionSchema = new Schema({ sellerId: { type: Schema.Types.ObjectId, required: true, ref: "Seller", index: true }, definitionId: { type: Schema.Types.ObjectId, required: true, ref: "JourneyDefinition", index: true }, version: { type: Number, required: true, min: 1 }, name: { type: String, required: true, maxlength: 160 }, trigger: { kind: { type: String, enum: ["manual", "purchase_age_days", "birthday", "back_in_stock", "price_drop"], required: true }, ageDays: { type: Number, required: true, min: 0, max: 3660 }, birthday: { type: String, default: null }, previousStock: { type: Number, default: null }, currentStock: { type: Number, default: null }, previousPriceHuf: { type: Number, default: null }, currentPriceHuf: { type: Number, default: null }, referencePriceHuf: { type: Number, default: null }, privacyStatus: { type: String, default: null } }, steps: { type: [stepSchema], required: true }, ruleTemplateKey: { type: String, required: true }, ruleTemplateVersion: { type: Number, required: true, min: 1 }, publishedByUserId: { type: Schema.Types.ObjectId, required: true, ref: "User" }, publishedAt: { type: Date, required: true } }, { versionKey: false, collection: "journey_definition_versions" });
versionSchema.index({ definitionId: 1, version: 1 }, { unique: true });

const enrollmentSchema = new Schema({ sellerId: { type: Schema.Types.ObjectId, required: true, ref: "Seller", index: true }, definitionId: { type: Schema.Types.ObjectId, required: true, ref: "JourneyDefinition", index: true }, definitionVersion: { type: Number, required: true }, buyerUserId: { type: Schema.Types.ObjectId, required: true, ref: "User", index: true }, customerId: { type: Schema.Types.ObjectId, required: true, ref: "Customer" }, status: { type: String, enum: ["active", "paused", "completed", "cancelled", "failed"], required: true, default: "active", index: true }, triggerEvidenceHash: { type: String, required: true, minlength: 64, maxlength: 64 }, triggeredAt: { type: Date, required: true }, nextRunAt: { type: Date, default: null, index: true }, completedAt: { type: Date, default: null }, failedAt: { type: Date, default: null }, reasonCode: { type: String, required: true, maxlength: 120 }, createdByUserId: { type: Schema.Types.ObjectId, required: true, ref: "User" } }, { ...timestamps, collection: "journey_enrollments" });
enrollmentSchema.index({ definitionId: 1, buyerUserId: 1, triggerEvidenceHash: 1 }, { unique: true });

const stepRunSchema = new Schema({ sellerId: { type: Schema.Types.ObjectId, required: true, ref: "Seller", index: true }, enrollmentId: { type: Schema.Types.ObjectId, required: true, ref: "JourneyEnrollment", index: true }, definitionId: { type: Schema.Types.ObjectId, required: true, ref: "JourneyDefinition", index: true }, definitionVersion: { type: Number, required: true }, buyerUserId: { type: Schema.Types.ObjectId, required: true, ref: "User", index: true }, customerId: { type: Schema.Types.ObjectId, required: true, ref: "Customer" }, stepKey: { type: String, required: true, maxlength: 60 }, stepIndex: { type: Number, required: true, min: 0 }, scheduledFor: { type: Date, required: true, index: true }, nextRunAt: { type: Date, required: true, index: true }, status: { type: String, enum: ["due", "processing", "retryable_failed", "completed", "skipped", "failed", "cancelled"], required: true, default: "due", index: true }, attemptCount: { type: Number, required: true, default: 0, min: 0, max: 3 }, maxAttempts: { type: Number, required: true, default: 3 }, lockedUntil: { type: Date, default: null }, lockedBy: { type: String, default: null, maxlength: 120 }, ruleSnapshot: { type: Schema.Types.Mixed, required: true }, contentSnapshot: { type: Schema.Types.Mixed, required: true }, deliveryId: { type: Schema.Types.ObjectId, default: null, ref: "DeliveryOutbox" }, reasonCode: { type: String, required: true, maxlength: 120 }, completedAt: { type: Date, default: null }, failedAt: { type: Date, default: null } }, { ...timestamps, collection: "journey_step_runs" });
stepRunSchema.index({ enrollmentId: 1, stepKey: 1, scheduledFor: 1 }, { unique: true });
stepRunSchema.index({ status: 1, nextRunAt: 1, lockedUntil: 1, _id: 1 });

for (const schema of [definitionSchema, versionSchema, enrollmentSchema, stepRunSchema]) schema.plugin(sellerScopedSchema);
export const JourneyDefinition = models.JourneyDefinition || model("JourneyDefinition", definitionSchema);
export const JourneyDefinitionVersion = models.JourneyDefinitionVersion || model("JourneyDefinitionVersion", versionSchema);
export const JourneyEnrollment = models.JourneyEnrollment || model("JourneyEnrollment", enrollmentSchema);
export const JourneyStepRun = models.JourneyStepRun || model("JourneyStepRun", stepRunSchema);
export const journeyModels = [JourneyDefinition, JourneyDefinitionVersion, JourneyEnrollment, JourneyStepRun];
